project_id = "zmsfntqgxsstnbpzdled"

[functions.firebird-query]
verify_jwt = false

[functions.sync-clientes]
verify_jwt = false

[functions.sync-produtos]
verify_jwt = false

[functions.sync-vendas]
verify_jwt = false

[functions.transform-dw]
verify_jwt = false

[functions.orchestrate-sync]
verify_jwt = false

[functions.sync-empresas]
verify_jwt = false

[functions.sync-agregados-diarios]
verify_jwt = false

[functions.sync-agregados-mensal]
verify_jwt = false

[functions.sync-agregados-semanal]
verify_jwt = false

[functions.ai-diretrizes]
verify_jwt = false

[functions.ai-central]
verify_jwt = false

[functions.sync-os-hub]
verify_jwt = false

[functions.ai-sugestao-cobertura]
verify_jwt = false

[functions.cache-diagnostico]
verify_jwt = false

[functions.hoya-proxy]
verify_jwt = false

[functions.bridge-health-check]
verify_jwt = false

[functions.ai-module-insights]
verify_jwt = false

[functions.btg-auth]
verify_jwt = false

[functions.btg-pagamentos]
verify_jwt = false

[functions.btg-cobrancas]
verify_jwt = false

[functions.btg-dda]
verify_jwt = false

[functions.btg-extrato]
verify_jwt = false

[functions.zeiss-proxy]
verify_jwt = false

[functions.btg-recebiveis-cartao]
verify_jwt = false
