project_id = "zmsfntqgxsstnbpzdled"

[functions.firebird-query]
verify_jwt = false

[functions.sync-clientes]
verify_jwt = false

[functions.sync-produtos]
verify_jwt = false

[functions.sync-vendas]
verify_jwt = false

[functions.transform-dw]
verify_jwt = false

[functions.orchestrate-sync]
verify_jwt = false

[functions.sync-empresas]
verify_jwt = false

[functions.sync-agregados-diarios]
verify_jwt = false

[functions.ai-diretrizes]
verify_jwt = false
