
-- Create table for DRE chart of accounts mapping
CREATE TABLE public.dre_plano_contas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conta_numero text NOT NULL,
  conta_descricao text NOT NULL,
  grupo_dre text NOT NULL,
  categoria text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(conta_numero)
);

ALTER TABLE public.dre_plano_contas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin full access dre_plano_contas" ON public.dre_plano_contas
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Authenticated read dre_plano_contas" ON public.dre_plano_contas
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Service role full access dre_plano_contas" ON public.dre_plano_contas
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Trigger for updated_at
CREATE TRIGGER update_dre_plano_contas_updated_at
  BEFORE UPDATE ON public.dre_plano_contas
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Seed with ERP accounts
INSERT INTO public.dre_plano_contas (conta_numero, conta_descricao, grupo_dre, categoria) VALUES
  -- RECEITAS (1.x)
  ('1.1', 'VENDAS DINHEIRO', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.2', 'VENDAS CHEQUE', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.3', 'VENDAS CARTAO CREDITO', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.4', 'VENDAS CARTAO DEBITO', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.5', 'VENDAS CONVENIO', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.6', 'VENDAS BOLETO', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.7', 'VENDAS PIX', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.8', 'VENDAS CREDIARIO', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.9', 'CREDITOS FORNECEDORES', 'RECEITA_BRUTA', 'VENDAS'),
  ('1.10', 'TRANSFERENCIA ENTRADA', 'RECEITA_BRUTA', 'OUTRAS_RECEITAS'),
  ('1.11', 'EMPRESTIMOS ENTRADA', 'RECEITA_BRUTA', 'OUTRAS_RECEITAS'),
  ('1.12', 'RECEITAS DIVERSAS', 'RECEITA_BRUTA', 'OUTRAS_RECEITAS'),
  ('1.13', 'CAIXA', 'RECEITA_BRUTA', 'VENDAS'),
  -- DEDUÇÕES (2.x)
  ('2.1', 'SIMPLES NACIONAL', 'DEDUCOES', 'IMPOSTOS'),
  ('2.2', 'COMISSOES', 'DEDUCOES', 'COMISSOES'),
  ('2.3', 'TAXAS ADQUIRENTES', 'DEDUCOES', 'TAXAS'),
  -- IMPOSTOS (3.1.x)
  ('3.1.1', 'TAXAS MUNICIPAIS', 'DEDUCOES', 'IMPOSTOS'),
  ('3.1.2', 'ICMS', 'DEDUCOES', 'IMPOSTOS'),
  ('3.1.3', 'IRPF', 'DEDUCOES', 'IMPOSTOS'),
  ('3.1.4', 'IRPJ', 'DEDUCOES', 'IMPOSTOS'),
  ('3.1.5', 'CSLL', 'DEDUCOES', 'IMPOSTOS'),
  ('3.1.6', 'PIS/COFINS', 'DEDUCOES', 'IMPOSTOS'),
  -- OCUPAÇÃO (3.2.x)
  ('3.2.1', 'ALUGUEL', 'DESPESAS_OPERACIONAIS', 'OCUPACAO'),
  ('3.2.2', 'CONDOMINIO', 'DESPESAS_OPERACIONAIS', 'OCUPACAO'),
  ('3.2.3', 'IPTU', 'DESPESAS_OPERACIONAIS', 'OCUPACAO'),
  ('3.2.4', 'AGUA', 'DESPESAS_OPERACIONAIS', 'OCUPACAO'),
  ('3.2.5', 'ENERGIA ELETRICA', 'DESPESAS_OPERACIONAIS', 'OCUPACAO'),
  ('3.2.6', 'GAS', 'DESPESAS_OPERACIONAIS', 'OCUPACAO'),
  ('3.2.7', 'SEGURO IMOVEL', 'DESPESAS_OPERACIONAIS', 'OCUPACAO'),
  -- COMUNICAÇÃO (3.3.x)
  ('3.3.1', 'TELEFONE', 'DESPESAS_OPERACIONAIS', 'COMUNICACAO'),
  ('3.3.2', 'INTERNET', 'DESPESAS_OPERACIONAIS', 'COMUNICACAO'),
  ('3.3.3', 'SOFTWARE/SISTEMAS', 'DESPESAS_OPERACIONAIS', 'COMUNICACAO'),
  ('3.3.4', 'CELULAR CORPORATIVO', 'DESPESAS_OPERACIONAIS', 'COMUNICACAO'),
  -- PESSOAL (3.4.x)
  ('3.4.1', 'SALARIO', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.2', 'FGTS', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.3', 'INSS', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.4', 'VALE TRANSPORTE', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.5', 'VALE ALIMENTACAO', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.6', 'PLANO SAUDE', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.7', 'FERIAS', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.8', 'DECIMO TERCEIRO', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.9', 'RESCISAO', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  ('3.4.10', 'EXAMES MEDICOS', 'DESPESAS_OPERACIONAIS', 'PESSOAL'),
  -- MARKETING (3.5.x)
  ('3.5.1', 'PUBLICIDADE', 'DESPESAS_OPERACIONAIS', 'MARKETING'),
  ('3.5.2', 'BRINDES', 'DESPESAS_OPERACIONAIS', 'MARKETING'),
  ('3.5.3', 'EVENTOS', 'DESPESAS_OPERACIONAIS', 'MARKETING'),
  -- FINANCEIRO OPERACIONAL (3.6.x)
  ('3.6.1', 'TARIFAS BANCARIAS', 'DESPESAS_OPERACIONAIS', 'FINANCEIRO_OPERACIONAL'),
  ('3.6.2', 'JUROS PAGOS', 'DESPESAS_OPERACIONAIS', 'FINANCEIRO_OPERACIONAL'),
  ('3.6.3', 'REEMBOLSOS', 'DESPESAS_OPERACIONAIS', 'FINANCEIRO_OPERACIONAL'),
  -- ADMINISTRATIVO (3.7.x)
  ('3.7.1', 'MATERIAL ESCRITORIO', 'DESPESAS_OPERACIONAIS', 'ADMINISTRATIVO'),
  ('3.7.2', 'EMBALAGENS', 'DESPESAS_OPERACIONAIS', 'ADMINISTRATIVO'),
  ('3.7.3', 'CORREIOS', 'DESPESAS_OPERACIONAIS', 'ADMINISTRATIVO'),
  ('3.7.4', 'CONTABILIDADE', 'DESPESAS_OPERACIONAIS', 'ADMINISTRATIVO'),
  ('3.7.5', 'ASSESSORIA JURIDICA', 'DESPESAS_OPERACIONAIS', 'ADMINISTRATIVO'),
  -- FORNECEDORES PRODUTO (3.8.x)
  ('3.8.1', 'FORNECEDORES LENTES', 'CUSTO_MERCADORIA', 'FORNECEDORES_PRODUTO'),
  ('3.8.2', 'FORNECEDORES ARMACOES', 'CUSTO_MERCADORIA', 'FORNECEDORES_PRODUTO'),
  ('3.8.3', 'FORNECEDORES ACESSORIOS', 'CUSTO_MERCADORIA', 'FORNECEDORES_PRODUTO'),
  ('3.8.4', 'FORNECEDORES SOLAR', 'CUSTO_MERCADORIA', 'FORNECEDORES_PRODUTO'),
  ('3.8.5', 'FORNECEDORES LENTES CONTATO', 'CUSTO_MERCADORIA', 'FORNECEDORES_PRODUTO'),
  -- SERVIÇOS (3.9.x)
  ('3.9.1', 'FRANQUIA', 'DESPESAS_OPERACIONAIS', 'SERVICOS'),
  ('3.9.2', 'MEDICOS', 'DESPESAS_OPERACIONAIS', 'SERVICOS'),
  ('3.9.3', 'LABORATORIO', 'DESPESAS_OPERACIONAIS', 'SERVICOS'),
  -- MANUTENÇÃO (3.10.x)
  ('3.10.1', 'MANUTENCAO PREDIAL', 'DESPESAS_OPERACIONAIS', 'MANUTENCAO'),
  ('3.10.2', 'DEDETIZACAO', 'DESPESAS_OPERACIONAIS', 'MANUTENCAO'),
  ('3.10.3', 'LIMPEZA', 'DESPESAS_OPERACIONAIS', 'MANUTENCAO'),
  -- DEVOLUÇÕES (3.11)
  ('3.11', 'CREDITOS DE CLIENTES', 'OUTRAS_DESPESAS', 'DEVOLUCOES'),
  -- FINANCEIRO (4.x)
  ('4.1', 'EMPRESTIMOS', 'OUTRAS_DESPESAS', 'FINANCEIRO'),
  ('4.2', 'JUROS FINANCIAMENTO', 'OUTRAS_DESPESAS', 'FINANCEIRO'),
  ('4.3', 'IOF', 'OUTRAS_DESPESAS', 'FINANCEIRO'),
  -- INVESTIMENTOS (5.x)
  ('5.1', 'SOFTWARE/EQUIPAMENTOS', 'INVESTIMENTOS', 'INVESTIMENTOS'),
  ('5.2', 'VEICULOS', 'INVESTIMENTOS', 'INVESTIMENTOS'),
  ('5.3', 'REFORMAS', 'INVESTIMENTOS', 'INVESTIMENTOS'),
  -- PRÓ-LABORE (6.x)
  ('6.1', 'RETIRADA MENSAL', 'OUTRAS_DESPESAS', 'PRO_LABORE');
